on:
  workflow_call:

jobs:
  bump_version:
    name: Bump package.json version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config --global user.name "RNB-BotRelease"
          git config --global user.email "jeremy.dolle34@gmail.com"
          npm --no-git-tag-version version ${{ github.event.release.tag_name }}
      - name: Commit and push
        run: |
          git add .
          git commit -am "🏷️(version) Update boilerplate to version ${{ github.event.release.tag_name }}"
          git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
