// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    // {
    //   type: 'category',
    //   label: 'Installation',
    //   items: [
    //     'installation/installation',
    //     'installation/configuration',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Guides',
    //   items: [
    //     'guides/theme',
    //     'guides/themes-and-dark-mode',
    //     'guides/splash-screen-loading-data',
    //     'guides/reduxStore',
    //     'guides/addALangTranslation',
    //   ],
    // },
  ],
};

module.exports = sidebars;
